language: go

notifications:
  email: false

env:
  global:
    - secure: "YpljiihWqxHSx/CX9eOzQkm0qXAl2EDbxliMCnzxKdjHKg/Tq+KkqTwwJseUBVfBxc86XQWZu5OIr+sXN/ElF3kQthSz8PinXQa0W1hEwzi5oFQLz7VmSWuxMmgvcwPkoRt5+ebR+ohkRYGbYLdzLjsrHaSnNtkoWHYRieE6/Lg="
    - PATH=$HOME/gopath/bin:$PATH

# TODO(u): Update import path of vet and cover when Travis starts using Go 1.4.

before_install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get code.google.com/p/go.tools/cmd/vet
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/golang/lint/golint
  - go get github.com/mattn/goveralls

install:
  - go get ./...

before_script:
  - wget https://gist.githubusercontent.com/mewmew/379014c9a2e6885e238d/raw/fb0c7d164113b1428f886dd470a613c74b9a9997/goclean.sh
  - chmod +x goclean.sh

script:
  - ./goclean.sh
